name: test panrom
on:
  push:
    branches:
      - main
jobs:
 testing-backend:
  runs-on: ubuntu-latest
  steps:
    - name: download code
      uses: actions/checkout@v4
    - name: install nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: install pacakges
      run: npm ci
    - name : testing the process
      run: npm test